#!/usr/bin/bash

HELP() {
  cat <<'EOF'
Usage: vrc-py_wrapper [-v] [ OPERATION [SWITCH] args ]

A CLI for managing and cycling VRChat OSC chatbox messages.

replace MESSAGE MESSAGE ...
  Replace all enabled message entries in config file with new entries.

disable ENTRY ENTRY ...
  Disable message entries.

delete ENTRY ENTRY ...
  Delete message entries.

enable ENTRY ENTRY ...
  Enable message entries.

append MESSAGE MESSAGE ...
  Append message entries to config.


--purge-entries
  Purge disabled message entries.

--print-config
  Print config file.

--print-enabled|--print-entries
  Print enabled message entries.

--print-disabled
  Print disabled message entries.

--init-config
  Initializes a new config file with example uses.

--verbose|-v
  Prints current timeout and message.

--help
  Print this message.
EOF
}
CONFIG_PATH="$HOME/.config/vrc-py"
PROFILE_PATH="$CONFIG_PATH/profiles"
CONFIG_FILE="$CONFIG_PATH/messages"
timeout=30
numbered_prefix=") -"
trap 'kill "$PROC_PID" && unset PROC_PID' SIGINT SIGTERM SIGHUP


######   Helpers   ######

START_VRC_PY() {
  coproc PROC { vrc-py; }
  exec {VRCFD}>&"${PROC[1]}"
}

STOP_VRC_PY() {
  if [ -n "$PROC_PID" ]; then
    kill "$PROC_PID"
    exec {VRCFD}>&-
    unset PROC PROC_PID
    return 0
  fi
  return 1
}

# Sorts args array in ascending order
sort_entries() {
  mapfile -t args < <(sort -nu < <(printf '%s\n' ${args[@]}))
}

# Errors if function is given one or less args
check_messages_null() {
  if [ -z "$(printf '%s\n' "${@:2}")" ]; then
    tee <<< "No message(s) (entries) provided."
    return 1
  else
    if [ -v "VRC_PY_WRAPPER_VERBOSE" ]; then
      messages=("$@:2")
      tee <<<"${message[*]}"
    fi
  fi
}

# Initialize config path and file
init_config() {

  # Create a new config if not present
  if [ "$1" = "init" ] || ! [ -e "$CONFIG_FILE" ]; then 
    # Init a new config
    local contents
    contents="$(cat <<'EOF'
message=This is a wrapper.
message="Some quote" - Some Person
message=Don't be mean >^\\\^<
EOF
)"
  fi
  mkdir -p "$PROFILE_PATH"
  tee <<<"$contents" "$CONFIG_FILE"
}


######   MAIN   ######

# Prints messages from given config
get_messages() {
  declare config="$1"
  sed -e "/^[[:space:]]*#/d;s/^.*=//" "$config"
#  eval "messages=($(
#    awk '
#    {
#      if (match($0,/^[^#]*message=(.*)$/, message)) {
#        $0 = message[1]
#        # Escape single quotes
#        gsub(/'\''/,"'\'\\\\\'\''")
#        # Extract message
#        printf "'\''%s'\''\n", $0
#      }
#    }
#    ' "$CONFIG_FILE"
#  ))"
}

order_messages() {
  local newCONFIG
  local enabled disabled
  enabled="$(
    awk '
    {
      if (/^[^#]*message=.*$/) {
        print $0
      }
    }' "$CONFIG_FILE"
  )"
  disabled="$(
    awk '
    {
      if (/^[^#]*message=.*$/) {
        next
      } else {
        print $0
      }
    }' "$CONFIG_FILE"
  )"
  # Only insert new line when needed
  if [ -n "$disabled" ] && [ -n "$enabled" ]; then
    enabled="$enabled"$'\n'
  fi
  cat <<<"$enabled$disabled" >"$CONFIG_FILE"
}

# Print config with a line number prefix.
print_numbered_entries() {
  case "$1" in 
    all)
      awk -v prefix="$numbered_prefix" '
      /message=/ {
        print NR prefix $0
      }' "$CONFIG_FILE"
      ;;
    enabled)
      awk -v prefix="$numbered_prefix" '
      /^[^#]*message=.*$/ {
        print NR prefix $0
      }' "$CONFIG_FILE"
      ;;
    disabled)
      awk -v prefix="$numbered_prefix" '
      /^[#[:space:]]+message=.*$/ {
        print NR prefix $0
      }' "$CONFIG_FILE"
      ;;
  esac
}

edit_config () {
  # Operates on the messagtes array and the config file.
  # preserve-disabled: Preserve disabled entries
  # preserve-enabled: Preserve enabled entries
  # preserve-all: Preserve all entries
  # enable-all: Preserve and enable all entries
  # disable-all: Preserve but disable all entries
  # enable: Enable provided entries
  # disable: Disable provided entries


  case "$1" in 
    preserve-disabled)
      newCONFIG="$(
        sed '/^[^#]*message=.*$/d' "$CONFIG_FILE"
      )"
      ;;
    preserve-enabled)
      newCONFIG="$(
        sed '/^[[:space:]]*#[[:space:]]*message=.*$/d' "$CONFIG_FILE"
      )"
      ;;
    preserve-all)
      newCONFIG="$(
        cat "$CONFIG_FILE"
      )"
      ;;
    delete-all)
      cat <<<"" > "$CONFIG_FILE"
      return
      ;;
    delete)

      sort_entries
      newCONFIG="$(
        cat "$CONFIG_FILE"
      )"
      local i=0
      for entry in "${args[@]}"; do
        newCONFIG="$(
          sed "$((entry - i))d" <<< "$newCONFIG"
        )"
        ((i++))
      done
      args=()
      ;;
    enable-all)
      newCONFIG="$(
        sed 's/^.*#.*\(message=.*\)$/\1/' "$CONFIG_FILE"
      )"
      ;;
    disable-all)
      newCONFIG="$(
        sed 's/^[^#]*\(message=.*\)$/# \1/' "$CONFIG_FILE"
      )"
      ;;
    disable)
      # Here $args is an array of entry numbers

      sort_entries
      newCONFIG="$(
        cat "$CONFIG_FILE"
      )"
      # Store enabled messages prior to removal
      mapfile -t enabledMessages < <(
        for message in "${args[@]}"; do
          #sed "$( IFS=$'\n' sed "${message}d;s/^\(.*\)$/\1d;/g" <<< "{1..$(wc -l "$CONFIG_FILE")}" )" "$CONFIG_FILE"
          awk -v target="$message" '
          {
            if (NR == target && match($0,/^[^#]*message=(.*)$/,message)) {
              // Enabled target
              print message[1]
              exit
            } else {
              next
            }
          }' <<<"$newCONFIG"
        done
      )
      # Remove messages
      local i
      for ((i=0;i<${#args[@]};i++)); do
        newCONFIG="$(IFS=$'\n' sed "$((${args[$((i+1))]} - i))d" <<< "$newCONFIG")"
      done
      if [ -n "${enabledMessages[*]}" ]; then
        # Concat messages
        newCONFIG="$(printf '# message=%s\n' "${enabledMessages[@]}")"$'\n'"${newCONFIG}"
      else 
        return 1
      fi
      args=()
      ;;
    enable)
      # Here $messages is an array of entry numbers

      sort_entries
      newCONFIG="$(cat "$CONFIG_FILE")"
      # Store messages prior to removal
      mapfile -t disabledMessages < <(
        for message in "${args[@]}"; do
          awk -v target="$message" '
          {
            if (NR == target && match($0,/^.*#.*message=(.*)$/,message)) {
              print message[1]
              exit
            } else {
              next
            }
          }' <<<"$newCONFIG"
        done
        )
      # Remove messages
      local i=0
      for message in "${args[@]}"; do
        newCONFIG="$(IFS=$'\n' sed "$((message - i))d" <<< "$newCONFIG")"
        ((i++))
      done
      if [ -n "${disabledMessages[*]}" ]; then
        # Concat messages
        newCONFIG="${newCONFIG}$(printf '\nmessage=%s' "${disabledMessages[@]}")"
      else 
        return 1
      fi
      args=()
      ;;
    *)
      tee <<< "Function: edit_config : Invalid action \`$1'"
      exit 1
      ;;
  esac

  # Construct final config
  newCONFIG="$newCONFIG""$(
    if [ -n "${args[*]}" ]; then
      printf '\nmessage=%s' "${args[@]}"
    fi
  )"

  cat <<< "$newCONFIG" >"$CONFIG_FILE"
  print_numbered_entries all
}

main() {
  local oldMessages=() messages=()
  mapfile -t messages < <(get_messages "$CONFIG_FILE")
  if [ -z "${messages[*]}" ]; then
    echo "No messages in config."
    exit 1
  fi
  START_VRC_PY
  printf "\`%s'\n" "${messages[@]}"
  while [ -n "$PROC_PID" ]; do 
    oldMessages=("${messages[@]}")
    mapfile -t messages < <(get_messages "$CONFIG_FILE")
    
    if [ -v "VRC_PY_WRAPPER_VERBOSE" ]; then
      [ "${oldMessages[*]}" = "${messages[*]}" ] || printf "\n\`%s'\n" "${messages[@]}"
    fi

    for message in "${messages[@]}"; do
      if [ -z "$PROC_PID" ]; then
        STOP_VRC_PY
        printf '\n'
        break
      fi
      printf '%s\n' "$message" >&"$VRCFD"
      
      # Timeout
      for time in $(seq 1 "$timeout"); do
        if [ -v "VRC_PY_WRAPPER_VERBOSE" ]; then
          printf '\033[2k\r%s' "Message \`${message}': Sleeping ${time}/${timeout}"
        fi
        sleep 1
        if [ -z "$PROC_PID" ]; then
          break
        fi
      done
    done
  done
}

order_messages
args=("$0" "$@")
parse_args() {
  case "${args[1]}" in
    "")
      main
      ;;

    ### OPTIONS ###

    --verbose|-v)
      VRC_PY_WRAPPER_VERBOSE=true
      args=("$0" "${args[@]:2}")
      parse_args
      ;;
    --prune|-p)
      edit_config preserve-enabled
      args=("$0" "${args[@]:2}")
      parse_args
      ;;
    --disabled-prefix)
      numbered_prefix="${args[2]}"
      args=("$0" "${args[@]:3}")
      parse_args
      ;;

    ### ACTION @@@

    disable)
      if grep -E "all|a" <<<"${args[2]}"; then
        edit_config disable-all
      else
        args=("${args[@]:2}")
        edit_config disable
      fi
      ;;
    delete)
      args=("${args[@]:2}")
      edit_config delete
      ;;
    enable)
      if grep -E "all|a" <<<"${args[2]}"; then
        edit_config enable-all
      else
        args=("${args[@]:2}")
        edit_config enable
      fi
      ;;
    replace)
      if [ "${args[2]}" = "--delete" ]; then
        edit_config delete-enabled
      else
        args=("${args[@]:2}")
        edit_config disable-all
      fi
      ;;
    append)
      # Add message(s) to config
      args=("${args[@]:2}")
      edit_config preserve-all
      ;;
    init)
      # Initialize config with example uses
      init_config init
      ;;
    clear)
      edit_config delete-all
      ;;
    print)
      # Print configuration file
      print_numbered_entries all
      ;;
    --print-enabled)
      print_numbered_entries enabled
      ;;
    --print-disabled)
      print_numbered_entries disabled
      ;;
    --help)
      # Print help message
      HELP
      exit
      ;;
    *)
      printf 'Unsopported option: %s\n' "${args[1]}" 
      HELP
      exit 1
      ;;
  esac
}
parse_args
printf '\r%s' "n>^~^<n"