#!/usr/bin/bash

HELP() {
  cat <<'EOF'
Usage: vrc-py_wrapper [-v] [-vv|--verbose] [-p|--prune] [ OPERATION [SWITCH] args ]

A CLI for managing and cycling VRChat OSC chat box messages.

r[eplace] [--purge] MESSAGE MESSAGE ...
  Disable (or delete) all enabled message entries with new entries.

d[isable] (a|all) | ENTRY ENTRY ...
  Disable message entries.

de[lete] (a|all) | (disabled|enabled) | ENTRY ENTRY ...
  Delete message entries.

e[nable] (a|all) | ENTRY ENTRY ...
  Enable message entries.

a[ppend] MESSAGE MESSAGE ...
  Append message entries to config.

p[rint] [enabled|disabled]
  Print message entries.

c[lear]
  Wipe config

i[nit]
  Initialize a new config file with example uses.


-p|--purge
  Purge disabled message entries.

-v
  Print message changes to stdout

-vv|--verbose
  Print current timeout and message changes.

h|-h|--help
  Print this message.
EOF
}
CONFIG_PATH="$HOME/.config/vrc-py"
PROFILE_PATH="$CONFIG_PATH/profiles"
CONFIG_FILE="$CONFIG_PATH/messages"
timeout=30
NUMBERED_SUFFIX="${NUMBERED_SUFFIX:=") -"}"
trap 'kill "$PROC_PID" && unset PROC_PID' INT TERM HUP


######   Helpers   ######

parse_fail()
{
  if [ "${2:: 1}" = - ]; then
    printf 'Unrecognised %s: %s\n' "${1}" "${2}"
  else
    printf 'Unrecognised %s: %s\n' "${1}" "${2}"
  fi
  printf "Try: vrc-py_wrapper --help"
  exit 1
}

START_VRC_PY()
{
  coproc PROC { vrc-py; }
  exec {VRCFD}>&"${PROC[1]}"
}

STOP_VRC_PY()
{
  if [ -n "$PROC_PID" ]; then
    kill "$PROC_PID"
    exec {VRCFD}>&-
    unset PROC PROC_PID
    return 0
  fi
  return 1
}

# Sorts entries in ascending order
sort_entries()
{
  sort -nu < <(printf '%s\n' "${@}")
}

# Initialize config path and file
init_config()
{
  # Create a new config if not present
  if [ "$1" = "init" ] || ! [ -e "$CONFIG_FILE" ]; then 
    # Init a new config
    local contents
    contents="$(cat <<'EOF'
message=This is a wrapper.
message="Some quote" - Some Person
message=https://github.com/farax3/vrc-py_wrapper
EOF
)"
  fi
  mkdir -p "$PROFILE_PATH"
  tee <<<"$contents" "$CONFIG_FILE"
}


######   MAIN   ######

# Prints messages from given config
get_messages()
{
  local config="$1"
  sed -e "/^[[:space:]]*#/d;s/^.*=//" "$config"
#  eval "messages=($(
#    awk '
#    {
#      if (match($0,/^[^#]*message=(.*)$/, message)) {
#        $0 = message[1]
#        # Escape single quotes
#        gsub(/'\''/,"'\'\\\\\'\''")
#        # Extract message
#        printf "'\''%s'\''\n", $0
#      }
#    }
#    ' "$CONFIG_FILE"
#  ))"
}

order_messages()
{
  local newCONFIG
  local enabled disabled
  enabled="$(
    awk '
    {
      if (/^[^#]*message=.*$/) {
        print $0
      }
    }' "$CONFIG_FILE"
  )"
  disabled="$(
    awk '
    {
      if (/^[^#]*message=.*$/) {
        next
      } else {
        print $0
      }
    }' "$CONFIG_FILE"
  )"
  # Only insert new line when needed
  if [ -n "$disabled" ] && [ -n "$enabled" ]; then
    enabled="$enabled"$'\n'
  fi
  cat <<<"$enabled$disabled" >"$CONFIG_FILE"
}

# Print config with a line number prefix.
print_numbered_entries()
{
  print_numbered()
  {
    awk -v prefix="$NUMBERED_SUFFIX" '
    /message=/ {
      print NR prefix $0
    }' "$CONFIG_FILE"
  }
  case "$1" in 
    all)
      print_numbered
      ;;
    enabled)
      print_numbered | sed -n '/^[^#]*[[:space:]]*message=/p'
      ;;
    disabled)
      print_numbered | sed -n '/^#[[:space:]]*message=/p'
      ;;
  esac
}

# append: Append provided entries
# enable: Enable provided entries
# disable: Disable provided entries
# enable-all: Enable all entries
# disable-all: Disable all entries
# remove-enabled: Remove enabled entries
# remove-disabled: Remove disabled entries
# remove-all: Remove all entries
edit_config()
{
  local action="$1"
  shift
  newCONFIG="$(cat "$CONFIG_FILE")"

  # Takes a sorted and unique list of entries and removes them from the config
  delete_lines()
  {
    local i entries=("$@")
    for ((i=0;i<${#entries[@]};i++)); do
      entry="$((entries[i] - i))"
      if [ $entry -gt "$(wc -l <<<"$newCONFIG")" ]
      then
        echo "Entry \`$entry' out of range"
      else
        newCONFIG="$(IFS=$'\n' sed "${entry}d" <<< "$newCONFIG")"
      fi
    done
  }

  case "$action" in 
    remove-enabled)
      newCONFIG="$(
        sed '/^[^#]*message=.*$/d' "$CONFIG_FILE"
      )"
      ;;
    remove-disabled)
      newCONFIG="$(
        sed '/^[[:space:]]*#[[:space:]]*message=.*$/d' "$CONFIG_FILE"
      )"
      ;;
    remove-all)
      cat <<< "" > "$CONFIG_FILE"
      return
      ;;
    append)
      # Handled at end of function.
      ;;
    delete)
      local entries=("${@}")
      mapfile -t entries < <(sort_entries "${entries[@]}")
      delete_lines "${entries[@]}"
      shift ${#entries[@]} # Consume positional
      ;;
    enable-all)
      newCONFIG="$(
        #shellcheck disable=2001
        sed 's/^[[:space:]]*#[[:space:]]*\(message=.*\)$/\1/' <<<"$newCONFIG"
      )"
      ;;
    disable-all)
      newCONFIG="$(
        sed 's/^[^#]*\(message=.*\)$/# \1/' "$CONFIG_FILE"
      )"
      ;;
    disable)
      local entries=("$@")
      mapfile -t entries < <(sort_entries "${entries[@]}")

      newCONFIG="$(
        cat "$CONFIG_FILE"
      )"
      # Store enabled messages prior to removal
      mapfile -t enabledMessages < <(
        for message in "${entries[@]}"; do
          #sed -n "$message{s/^[^#]*message=\(.*\)/\\1/p}" "$CONFIG_FILE"
          awk -v target="$message" '
          {
            if (NR == target && match($0,/^[^#]*message=(.*)$/,message)) {
              // Enabled target
              print message[1]
              exit
            } else {
              next
            }
          }' <<<"$newCONFIG"
        done
      )
      delete_lines "${entries[@]}"
      shift ${#entries[@]} # Consume positional
      if [ -n "${enabledMessages[*]}" ]; then
        # Concat messages
        newCONFIG="$(printf '# message=%s\n' "${enabledMessages[@]}")"$'\n'"${newCONFIG}"
      else 
        return 1
      fi
      ;;
    enable)
      # Here $messages is an array of entry numbers
      local entries=("${@}")

      mapfile -t entries < <(sort_entries "${entries[@]}")
      newCONFIG="$(cat "$CONFIG_FILE")"
      # Store messages prior to removal
      mapfile -t disabledMessages < <(
        for message in "${entries[@]}"; do
          awk -v target="$message" '
          {
            if (NR == target && match($0,/^.*#.*message=(.*)$/,message)) {
              print message[1]
              exit
            } else {
              next
            }
          }' <<<"$newCONFIG"
        done
        )
      delete_lines "${entries[@]}"
      shift ${#entries[@]} # Consume positional
      if [ -n "${disabledMessages[*]}" ]; then
        # Concat messages
        newCONFIG="${newCONFIG}$(printf '\nmessage=%s' "${disabledMessages[@]}")"
      else 
        return 1
      fi
      ;;
    *)
      tee <<< "Function: edit_config : Invalid action \`$action'"
      exit 1
      ;;
  esac

  # Construct final config
  newCONFIG="$newCONFIG""$(
    if [ -n "${*}" ]; then
      printf '\nmessage=%s' "${@}"
    fi
  )"

  cat <<< "$newCONFIG" >"$CONFIG_FILE"
}

main()
{
  local oldMessages=() messages=()
  mapfile -t messages < <(get_messages "$CONFIG_FILE")
  if [ -z "${messages[*]}" ]; then
    echo "No messages enabled."
    exit 1
  fi
  START_VRC_PY
  print_numbered_entries enabled
  while [ -n "$PROC_PID" ]; do 
    oldMessages=("${messages[@]:-}")
    mapfile -t messages < <(get_messages "$CONFIG_FILE")
    
    if [ -v "VRC_PY_WRAPPER_VERBOSE" ]; then
      [ "${oldMessages[*]}" = "${messages[*]}" ] || print_numbered_entries enabled
    fi

    for message in "${messages[@]}"; do
      if [ -z "$PROC_PID" ]; then
        STOP_VRC_PY
        printf '\n'
        break
      fi
      printf '%s\n' "$message" >&"$VRCFD"
      
      # Timeout
      for time in $(seq 1 "$timeout"); do
        if [ "$VRC_PY_WRAPPER_VERBOSE" -gt -1 ] 2>/dev/null; then
          printf '\r\033[2k%s\r' "Message \`${message}': Sleeping ${time}/${timeout}"
        fi
        sleep 1
        if [ -z "$PROC_PID" ]; then
          break
        fi
      done
    done
  done
}

order_messages
args=("$0" "$@")
parse_args()
{
  case "${args[1]}" in
    "")
      main
      ;;

    ### OPTIONS ###

    --verbose|-vv)
      declare -gi VRC_PY_WRAPPER_VERBOSE=0
      args=("$0" "${args[@]:2}")
      parse_args
      ;;
    -t)
      declare -g timeout="${args[2]}"
      args=("$0" "${args[@]:3}")
      parse_args
      ;;
    -v)
      declare -gi VRC_PY_WRAPPER_VERBOSE=-1
      args=("$0" "${args[@]:2}")
      parse_args
      ;;
    --prune|-p)
      edit_config remove-disabled >/dev/null
      args=("$0" "${args[@]:2}")
      parse_args
      ;;
    --disabled-prefix)
      NUMBERED_SUFFIX="${args[2]}"
      args=("$0" "${args[@]:3}")
      parse_args
      ;;

    ### ACTION @@@

    d|disable)
      if grep -E "^(all|a)$" <<<"${args[2]}"; then
        edit_config disable-all "${args[@]:3}"
      else
        edit_config disable "${args[@]:2}"
      fi
      ;;
    delete)
      case "${args[2]}" in
        disabled)
          edit_config remove-disabled "${args[@]:3}"
          ;;
        enabled)
          edit_config remove-enabled "${args[@]:3}"
          ;;
        all|a)
          edit_config remove-all
          ;;
        0)
          parse_fail entry "${args[2]}"
          ;;
        [0-9]*)
          edit_config delete "${args[@]:2}"
          ;;
        *)
          parse_fail switch "${args[2]}"
          ;;
      esac
      ;;
    e|enable)
      if grep -E "^(all|a)$" <<<"${args[2]}"; then
        edit_config enable-all "${args[@]:3}"
      else
        edit_config enable "${args[@]:2}"
      fi
      ;;
    r|replace)
      if [ "${args[2]}" = --purge ]; then
        # Purge enabled
        edit_config remove-enabled "${args[@:3]}" >/dev/null
      else
        # Disable enabled and append new
        edit_config disable-all "${args[@]:2}"
      fi
      ;;
    a|append)
      # Add message(s) to config
      edit_config append "${args[@]:2}"
      ;;
    i|init)
      # Initialize config with example uses
      init_config init "$CONFIG_FILE"
      ;;
    p|print)
      case "${args[2]}" in
        disabled)
          print_numbered_entries disabled
          ;;
        enabled)
          print_numbered_entries enabled
          ;;
        "")
          print_numbered_entries all
          ;;
        *)
          parse_fail subcommand "${args[2]}"
          ;;
      esac
      ;;
    h|-h|--help)
      # Print help message
      HELP
      exit
      ;;
    *)
      parse_fail subcommand "${args[1]}"
      ;;
  esac
}
parse_args
printf '\r%s' "n>^~^<n" >&2